language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - PACKAGE="ocplib-json-typed" OCAML_VERSION="4.03" DEPOPTS="js_of_ocaml ocplib-endian"
  - PACKAGE="ocplib-json-typed" OCAML_VERSION="4.04" DEPOPTS="js_of_ocaml ocplib-endian"
  - PACKAGE="ocplib-json-typed" OCAML_VERSION="4.06" DEPOPTS="js_of_ocaml ocplib-endian"
  - PACKAGE="ocplib-json-typed" OCAML_VERSION="4.07" DEPOPTS="js_of_ocaml ocplib-endian"
